### ISSUE TITLE
Correct Regex? I want to blacklist this entire website, but nothing I try works.

### ISSUE THREAD

**Issue by gaveitatry2** [gediminasel/videospeed-firefox#11]
**UPDATE:**

The correct Regex format was:

`app.chatwebsite.com`

- - - - - - - - - - - - - - - - - - -

I have a website like this https://app.chatwebsite.com/room/lounge/randompersonsname

I want to disable Video Speed Controller for that entire website so that the control box does not show up on the videos.

I wanted to do something simple like this:

`*chatwebsite.com*`

`https://app.chatwebsite.com*`

but that didn't work.

So I tried figuring out Regex and tried:

`https://app.chatwebsite.com/.`

`https://app.chatwebsite.com/.*`

`/?(?<=chatwebsite.*)$`

and some others, but they also did not work.

What is the correct format?

**Comment by gaveitatry2** [comment]
Hello?

**Comment by gaveitatry2** [comment]
@gediminasel  - Can I please get some help? I just want to completely blacklist this one entire website so that the controller never shows up on it. But I don't know Regex and my guess attempts all failed. This would probably take you five seconds to answer. But I'm waiting months with no reply. Please help.

**Comment by gediminasel** [comment]
Hi, have you tried simply `app.chatwebsite.com` or `chatwebsite.com`?

**Comment by gaveitatry2** [comment]
> Hi, have you tried simply `app.chatwebsite.com` or `chatwebsite.com`?

Awesome, that works. Thank you!
